name: shotwell
adopt-info: shotwell
grade: stable
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  shotwell:
    interface: dbus
    bus: session
    name: org.gnome.Shotwell

apps:
  shotwell:
    command: usr/bin/shotwell
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Shotwell.desktop
    environment:
      HOME: $SNAP_USER_COMMON
    plugs:
      - audio-playback
      - home
      - mount-observe
      - hardware-observe

parts:
  shotwell:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/shotwell.git
    source-tag: shotwell-0.32.1
    meson-parameters:
      - --prefix=/usr
    parse-info: [usr/share/metainfo/org.gnome.Shotwell.appdata.xml]
    build-packages:
      - cmake
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgphoto2-dev
      - libgexiv2-dev
      - libraw-dev
    stage-packages:
      - libexif12
      - libgcr-ui-3-1
      - libgdata22
      - libgexiv2-2
      - libgphoto2-6
      - libgphoto2-port12
      - libraw20
  cleanup:
    after: [shotwell]
    plugin: nil
    build-snaps: [core22, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* \
          -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      for snap in "core22"; do
        cd "/snap/$snap/current/usr/lib"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET/$filename"
        done
        cd "/snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$filename"
        done
      done
