name: shotwell
adopt-info: shotwell
grade: stable
confinement: strict
base: core24

slots:
  # for GtkApplication registration
  shotwell:
    interface: dbus
    bus: session
    name: org.gnome.Shotwell

layout:
  /usr/libexec:
    bind: $SNAP/usr/libexec
  /usr/share/shotwell:
    bind: $SNAP/usr/share/shotwell

apps:
  shotwell:
    command: launch.sh $SNAP/usr/bin/shotwell
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Shotwell.desktop
    environment:
      HOME: $SNAP_USER_COMMON
    plugs:
      - audio-playback
      - home
      - raw-usb
      - mount-observe
      - hardware-observe
      - removable-media

parts:
  scripts:
    plugin: dump
    source: ./scripts

  shotwell:
# ext:updatesnap
#   version-format:
#     format: "shotwell-%M.%m.%R"
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/shotwell.git
    source-tag: shotwell-0.32.10
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
      - -Dunity_support=true
      - -Dface_detection=true
    build-environment:
      - LD_LIBRARY_PATH: "${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}\
                          /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunity"
    parse-info: [usr/share/metainfo/org.gnome.Shotwell.appdata.xml]
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/0.32.10.patch
    build-packages:
      - cmake
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgphoto2-dev
      - libgexiv2-dev
      - libraw-dev
      - libmtp-dev
      - libopencv-dev
    stage-packages:
      - libexif12
      - libgcr-ui-3-1
      - libgdata22
      - libgexiv2-2
      - libgphoto2-6t64
      - libgphoto2-port12t64
      - libraw23t64
      - libmtp9t64
      - libopencv-core406t64
      - libxerces-c3.2t64
      - liburiparser1
      - libsz2
      - libarmadillo12
      - libopenexr-3-1-30
      - libpq5
      - libprotobuf32t64
      - libqhull-r8.0
      - libsnappy1v5
      - libblosc1
      - libcfitsio10t64
      - libcharls2
      - libhdf4-0-alt
      - libfreexl1
      - libfyba0t64
      - libfyba0t64
      - libfyba0t64
      - libgdal34t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgdcm3.0t64
      - libgeos3.12.1t64
      - libgeos-c1t64
      - libgeotiff5
      - libgif7
      - libhdf5-103-1t64
      - libhdf5-hl-100t64
      - libkmlbase1t64
      - libkmldom1t64
      - libkmlengine1t64
      - libhdf4-0-alt
      - libminizip1t64
      - libmysqlclient21
      - libnetcdf19t64
      - libodbc2
      - libodbcinst2
      - libogdi4.1
      - libopencv-calib3d406t64
      - libopencv-dnn406t64
      - libopencv-features2d406t64
      - libopencv-flann406t64
      - libopencv-imgcodecs406t64
      - libopencv-imgproc406t64
      - libopencv-objdetect406t64
      - libproj25
      - librttopo1
      - libspatialite8t64

  cleanup:
    after: [shotwell]
    plugin: nil
    build-snaps: [core24, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* \
          -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      for snap in "core24" "gnome-46-2404"; do
        cd "/snap/$snap/current/usr/lib"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$filename"
        done
        cd "/snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
        for filename in [ *.so* ]; do
          rm -f "$CRAFT_PRIME/usr/lib/$filename"
        done
      done
